all:
	g++ -std=c++11 -mavx2 -mfma -I/home/ranil/ishaan66@github.io/include/opencv -I/home/ranil/ishaan66@github.io/include/opencv2 -L/home/ranil/ishaan66@github.io/lib/ -g -o my_serial.o hough.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui

clean:
	rm -rf *.o *~
